import Head from 'next/head'
import Image from 'next/image'
import {Container, Row, Col} from 'react-bootstrap'

export default function Portofolio() {
  return (
    <Container>
      <Head>
        <title>Portofolio - Practice Next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main >
            <h1>
            This page Portofolio
            </h1>
        </main>
      </Container>
  )
}