import Head from 'next/head'
import Image from 'next/image'
import {Container, Row, Col} from 'react-bootstrap'
import styles from '../styles/Template.module.css'

export default function Template() {
  return (
    <Container>
      <Head>
        <title>Template - Practice Next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
            <h1>
            This page Template
            </h1>
        </main>
      </Container>
  )
}